//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ГимаевДЭ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public string Articul { get; set; }
        public string Title { get; set; }
        public string Ez { get; set; }
        public decimal Cost { get; set; }
        public double MaxDiscount { get; set; }
        public int IDManufacture { get; set; }
        public int IDProvider { get; set; }
        public int IDProductKategory { get; set; }
        public double Discount { get; set; }
        public int Count { get; set; }
        public string Discreption { get; set; }
        public byte[] Image { get; set; }



        public string Background
        {
            get
            {
                return Discount > 15 ? "#7fff00" : "#ffffff";
            }
        }

        public string CostText
        {
            get
            {
                return Discount > 0 ? String.Format($"-{Cost:N2}- {Cost - (Cost * Convert.ToDecimal((Discount / 100))):N2} руб.") : $"{Cost:N2} руб.";
            }
        }


        public virtual Manufactures Manufactures { get; set; }
        public virtual ProductKategory ProductKategory { get; set; }
        public virtual Providers Providers { get; set; }
    }
}
